# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool: Default

variables: { agent.disablelogplugin.TestResultLogPlugin: 'false' }

steps:
- script: python SampleTests.py
  displayName: 'python run unit tests'